repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: "trailing-whitespace"
      - id: "check-case-conflict"
      - id: "check-merge-conflict"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
      - id: "detect-private-key"
      - id: "check-yaml"
      - id: "check-toml"
      - id: "check-json"
      - id: "mixed-line-ending"
        args: [ "--fix", "crlf" ]
        types:
          - python
          - yaml
          - toml
          - text

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [ "--fix" ]

      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
