[project]
name = "aiogram_i18n"
authors = [
    { name = "RootShinobi" },
]
description = "Translation tool for aiogram"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Typing :: Typed",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
keywords = [
    "telegram",
    "bot",
    "api",
    "framework",
    "wrapper",
    "asyncio",
    "i18n",
    "aiogram",
    "fluent",
    "gnutext",
]
dynamic = ["version"]
dependencies = [
    "aiogram>=3.0.0b8",
    "click==8.*",
]

[tool.uv]
package = true

[tool.hatch.version]
path = "aiogram_i18n/__meta__.py"

[project.urls]
Repository = "https://github.com/aiogram/aiogram_i18n"

[project.scripts]
i18n = "aiogram_i18n.__main__:main"

[project.optional-dependencies]
compiler = [
    "fluent_compiler~=1.1",
]
runtime = [
    "fluent.runtime~=0.4.0",
]
jinja2 = [
    "jinja2~=3.1.4",
]
test = [
    "pytest==8.4.2",
    "pytest-cov==7.0.0",
    "pytest-asyncio==1.2.0",
    "fluent.runtime==0.4.0",
    "coverage==7.11.0",
]
dev = [
    "isort==7.0.0",
    "pre-commit==4.3.0",
    "ruff==0.14.1",
    "mypy==1.18.2",
    "types-polib==1.2.0.20250401",
]
docs = [
    "sphinx==8.1.3",
    "furo==2025.9.25",
    "sphinx-autobuild==2024.10.3",
]

[tool.hatch.envs.dev]
post-install = [
    "pre-commit install",
]

features = [
    "compiler",
    "runtime",
    "jinja2",
    "dev",
    "test",
    "docs",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
exclude = [
    "\\.?venv",
    "\\.idea",
    "\\.tests?",
]

[[tool.mypy.overrides]]
module = "mre"
strict_optional = false

[[tool.mypy.overrides]]
module = "aiogram_i18n.types"
disable_error_code = ["arg-type", "assignment"]

[[tool.mypy.overrides]]
module = [
    "redis.*", "fluent_compiler.*"
]
ignore_missing_imports = true

[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "A002",
    "ANN001", "ANN003", "ANN204", "ANN401",
    "COM812",
    "CPY001",
    "D",
    "DOC",
    "FBT001", "FBT002",
    "N805",
    "PLC0415",
    "PLR0913", "PLR0917", "PLR1702", "PLR6301",
    "PLW2901",
    "TC006",
    "TID252",
]
unfixable = []
exclude = [
    "examples"
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**/*" = ["PLR2004", "S101", "TID252"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.isort]
py_version = 310
line_length = 99
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
split_on_trailing_comma = false
single_line_exclusions = ["."]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
skip_gitignore = true
extend_skip = ["__pycache__"]
