name: "🔧 Python tests and checks"

on:
  push:
    branches: [ "master", "main", "dev" ]
  pull_request:
    branches: [ "master", "main", "dev" ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - 'pypy3.9'

    defaults:
      # Windows sucks. Force use bash instead of PowerShell
      run:
        shell: bash

    runs-on: ${{ matrix.os }}

    env:
      # We disable some features for PyPy by this environment variable such as:
      # – Installation of `fast` extras: `uvloop` on PyPy is useless and may be even slower
      # than the default loop;
      # – Coverage reports: code introspection disables any optimizations, so tests with
      # coverage enabled are very slow on PyPy.
      # More: https://www.pypy.org/performance.html
      IS_PYPY: ${{ startswith(matrix.python-version, 'pypy') }}
      # Windows has also some limitations:
      # – Redis is not supported on GitHub Windows runners;
      IS_WINDOWS: ${{ startswith(matrix.os, 'windows') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          version: "latest"
          enable-cache: true

      - name: Install the project
        run: uv sync --extra dev --extra test --extra compiler --extra runtime --extra jinja2

      - name: Minimize uv cache
        run: uv cache prune --ci

      - name: Lint code
        if: "env.IS_PYPY == 'false'"
        run: make lint

      - name: Run tests
        run: make test-ci

      - name: Check installable
        run: |
          uv build
          uv run --verbose --with aiogram_i18n --no-project --refresh-package aiogram_i18n -- python -c "import aiogram_i18n; print(aiogram_i18n.__version__)"
